services:
  - type: web
    name: django-appointment
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && SKIP_DB_CONNECTION=1 python manage.py collectstatic --noinput
    startCommand: gunicorn appointments.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "django-appointment-u96d.onrender.com,*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-appointment-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: USE_DJANGO_Q
        value: "False"
      - key: APPOINTMENT_WEBSITE_NAME
        value: "Maw3idi"

databases:
  - name: django-appointment-db
    plan: free

