services:
  - type: web
    name: django-appointment
    env: python
    buildCommand: pip install -r requirements-prod.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn appointments.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "maw3idi.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-appointment-db
          property: connectionString
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: USE_DJANGO_Q
        value: "True"
      - key: APPOINTMENT_WEBSITE_NAME
        value: "Maw3idi"

  - type: worker
    name: django-appointment-worker
    env: python
    buildCommand: pip install -r requirements-prod.txt
    startCommand: python manage.py qcluster
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-appointment-db
          property: connectionString

databases:
  - name: django-appointment-db
    plan: free

